
server:
  port: 7777
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my-book?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  application:
    name: my-book
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  resources:
    static-locations: file:E:/my-book/upload/choice/
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.yayo: debug
  path: .